apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: apps
  labels:
    app: echoserver
spec:
  type: ClusterIP
  selector:
    app: echoserver
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
